### ISSUE TITLE
JCM Morphs are not automated/ No Pose Morphs? 

### ISSUE THREAD

**Issue by malikeena** [daz3d/DazToMaya#32]
Hey I'm sure you are already looking into this saw this on the last post. I was looking into the new update and everything seems working except that the JCMs are not activating on their own. It would be extremely convenient if we could get it set up with the pose editor. Not sure if you have another method but this would be a great feature. Other than that it's making amazing progress!
Looking forward to more updates, I can continue to test it and give more thoughts.

**Comment by danielbui78** [comment]
Thanks for the feedback!  I'm looking into this JCM issue in Maya.  I'm not 100% certain if it was working and stopped with the change to C++, or if it was not yet fully implemented in the original script-version of the bridge.  Thank you for your patience.

**Comment by stepharamburu** [comment]
Hi Daniel. is there any news about this point please? Best Regards! Steph

**Comment by danielbui78** [comment]
The JCM feature for Maya is roughly planned out, but there was unfortunately not enough time to implement for the recent update.  Will hopefully get it into the next one later  year.

**Comment by nickvisuals** [comment]
Been a few months....any updates on JCM support?

**Comment by stepharamburu** [comment]
Hi there. please any news about this topic?

**Comment by danielbui78** [comment]
I will try my best to get this feature into the next update.  ETA for update is mid Jan or Feb 2023.

**Comment by stepharamburu** [comment]
Hi there, waiting for some good news ;)

**Comment by danielbui78** [comment]
Will be working on JCM in addition to other Bridge updates this month (Feb).  Hopefully, will release near the last week of Feb. or early March.  Thanks for everyone's patience on the delays.

**Comment by malikeena** [comment]
Hey, Daniel wanted to check up on how it's going it's early March wanted to see if there is anything I can do to test and or help! JCMs working in maya would be an amazing feature, wanted to say have you seen DTL Daz to Unreal? Specifically, this does a lot of extra features that are really necessary, for example changing the orientation of the bones so that they match Unreal's structure. Maybe as you import there is a checkbox that you can click to fix bone rotations if you need to. They are also doing some things with HighRes JCMs but that may be too much and too time-consuming. I'm sure the JCMs alone are a lot but I truly feel that is what is necessary in order to make this process seamless. Hope to see some progress soon!

**Comment by stepharamburu** [comment]
Hi Daniel, if the new bridge to maya can improve a Motionbuilder skeleton structure on Human IK instead of the classic Maya default structure, it will be great !

**Comment by danielbui78** [comment]
There were more delays in other projects but the issues are now resolved, so I am just now reviewing open issues and planning a timeline for Bridge updates.  JCM support is still high on the priority list.

@malikeena Yes, I have been in very close communications with the author of the DTL Daz to Unreal -- their product is very good and I recommend it.

@stepharamburu Can you be more specific? Do you have a specific use-case or an issue with your workflow between Maya and Motionbuilder?

**Comment by stepharamburu** [comment]
Hi @danielbui78 There are different structure bones on twist bones between Maya Default (first) and Motionbuilder (second) as you can see on pics. The motionbuilder structure let you add extra twist controllers easily instead of the maya default if you want to work it with the Maya Rig`. Regards!!

![humanIK_1_default](https://user-images.githubusercontent.com/89225543/224457922-99178137-d116-4152-b542-8b4f78093aae.JPG)
![humanIK_1_motionbuilder_structure](https://user-images.githubusercontent.com/89225543/224457923-33a16981-9794-49b5-84b2-26743102a0ab.JPG)

**Comment by danielbui78** [comment]
https://github.com/daz3d/DazToMaya/releases/tag/2022.2.14-preview

**Comment by stepharamburu** [comment]
Hi Daniel, thank you so much for notified. From my side, automated JCMs still doesn't work also the subdivision bake option can't be applied. Character only can be imported on Base Resolution. Best Regards!

**Comment by crisjsalina** [comment]
JCMs work well on my side. You need to update both the plugin on the daz side and also on the maya side. 

As for the subdivision, yeah I'm having the same issue. The plugin is not exporting the HD morphs so all I get is a base resolution character in Maya.

Overall, I think with this JCMs addition the bridge has become a lot more useful. So thanks Daniel for not giving up on the bridges! They still needs some key features added, which I'm sure they will be. So thanks for your work :)

**Comment by stepharamburu** [comment]
I think I'm doing something wrong because it still doesn't work for me.  :(

**Comment by crisjsalina** [comment]
Hmm I only tried with a Gen 8.1 model, so perhaps it doesn't work with other models?

**Comment by Obaemon7** [comment]
HI there, thanks for the work, i've been waiting for a a long time for this.
However, when i have my model in maya i can see that all the morphs are in yellow, meaning they are all connected, but when i try to move the character, the blendshapes don't move. I tried with the controller and even directly on the bones but this doesn't work, i'm obvsiously doing something wrong.

**Comment by stepharamburu** [comment]
well I think we're doing something wrong because I have exactly the same issue. I tested with G-8.1 getting the same result but, @crisjsalina says it works fine.

**Comment by danielbui78** [comment]
I am developing a troubleshooting tool to help identify the problem.  Thanks for your patience.

**Comment by Obaemon7** [comment]
I think i'm installing this wrong.
I opened the Daz central (haven't launched it for almost a year), the Daz to maya plugins has automatically updated.
Now i see this:

![daztomaya_version](https://user-images.githubusercontent.com/130797127/232232197-75db7443-f9a0-4f16-bfec-6db99baa48de.jpg)

However if i look at the web page where i can download the last version:

![daztomaya_version2](https://user-images.githubusercontent.com/130797127/232232224-968639c2-a754-4763-be02-6e9f50e91169.jpg)

When i use the send to > DAZtomaya in Daz, i can select the export morphs button, so am i up to date ?

In maya i have this:
![shapes](https://user-images.githubusercontent.com/130797127/232233419-1f2b4578-246d-4a3f-9370-f8551204efff.jpg)

So you can see the blendshapes are yellow (connected to something), but they don't actually activate when i move the controllers (auto rig). I have raised the left arm wich should activate the shldrUp90_L, and i have put down the right arm wich should activate the shldrDown40_R

About the folders and files:

![daztomaya_version_folders](https://user-images.githubusercontent.com/130797127/232232531-bd62df47-ac60-43f0-89bc-c85d2bd7694c.jpg)

I have no idea where i should put the files for this preview version, the main page is saying that we should use the daz central to let daztomaya update. But i'm not sure this preview version is downloaded automatically, if not, i don't think it knows where to find those files on my computer, so i guess i need to copy them somewhere.

Thanks for the help

**Comment by Obaemon7** [comment]
i can also see that some expression are connected to something, like the mouth stretch, mouth pucker, smile etc.
I thought those where independant from any controllers, and since they are connected now, i wonder what controller should we move to activate them ? I'll see that further when i will be able to activate the shapes though.

**Comment by danielbui78** [comment]
@Obaemon7 Thanks, I understand your problem now.  The Auto-JCM is a preview release and not available through Daz Central or Daz Install Manager.  In order to use the Auto-JCM preview release, you should download the DLL plugin, then manually install it into Daz Studio, then use Daz Studio to install the Maya plugin to Maya:

1. Manually install a DLL plugin from Github release page using this video: https://youtu.be/LDDPfygZfgs
2. Once installed, check the DazToMaya Bridge version and make sure that it is now revision 14.38 in the Advanced Settings section.
3. Install the Maya plugin using Daz Studio bridge (time code 1:21): https://youtu.be/H3ukRuEyLCM?t=81
4. Once installed, Open the Daz To Maya Bridge dialog from inside Maya and then open your Maya Script Editor window and you should see some lines like these:

```
DazToMaya.run()
DazToMaya: Python Version is 3.7.7 final
DazToMaya: has successfully loaded, version v2022.2.14.38.
DazToMaya: Intermediate folder location is .....
```
Make sure it is version v2022.2.14.38.

Now follow the steps on the Auto-JCM prerelease page for testing auto-jcm feature.

**Comment by Obaemon7** [comment]
Thanks for your answer, i'm gonna try that.
Just to make sure, all of this is supposed to work for maya 2023 and/or 2022 ?

**Comment by danielbui78** [comment]
Yes, I have tested this pre-release version on Maya 2022.3, 2022.4 and 2023.3.  They should all support Auto-JCM, Auto-Rig, subdivision.

**Comment by Obaemon7** [comment]
ok thank you! i'm gonna try this !

**Comment by Obaemon7** [comment]
Ok, i've done all of this, and the blendshapes are now activating normally. Thanks for that !
I still have some issues. In maya 2023 the "Daz import" button in the daz to maya shelf doesn't work, the auto rig button works normally. I've seen someone mentionning a similary issue, i tried creating a new button with the python script you provided, but it didn't work, same result, ui window doesn't appears when a hit the button in the shelf.

But it's working in maya 2022.
More annoying issue, some blendshape don't really work, with the auto rig, if i move the controller for the eyes, i can see the eyes following, i can see the blendshapes value changing, but the geometry doesn't change on the mesh. 

![shapes_not_moving](https://user-images.githubusercontent.com/130797127/232251492-bb2f80aa-d5e2-4b15-a04d-6877004f5f2f.jpg)

For the project i'm working on, i tried doing the connections myself through the node editor, it was a nightmare doing them one by one (i feel you man), using a combination of multiply/divide, math float, max and min nodes (nightmare), i ended up with something working well but couldn't manage to have the shoulder working (because there's multiple blendshapes blending with each other and i couldn't figure it out). 

(That's why i was checking this post for months, since my final object is not the one rigged but an edited copy of it following it with a wrap deformer, i'm able to update the rig and don't loose my progress.)

However for the eyes i got it to work.
here's 2 exemples 

![down](https://user-images.githubusercontent.com/130797127/232251863-a680bae1-7eee-497e-a071-54d8ca03658a.jpg)


![up](https://user-images.githubusercontent.com/130797127/232251872-50fd3b5c-257b-4328-8a7f-2b2722a90931.jpg)

Same for the mouth, if i use the lower jaw controller to open it in this new version. I have this: 

![bad_mouth](https://user-images.githubusercontent.com/130797127/232251894-cc2be37b-8ddc-49dd-a077-aa29dc90bccf.jpg)

I had the same issue before so i decided to not use that controller at all, and create a new one (the pink one), with only blendshape connections in it (not connected to any bones, so when i move the controller, it only activate blendshapes):

![mouth_good](https://user-images.githubusercontent.com/130797127/232252371-0f36e3d5-4710-4602-b67d-ad2a9e30a6a0.jpg)


So currently, the blendshapes for the face are not moving the Geo, and as i say before, the expressions ones, like smile, squint etc, are now connected, but i don't know to what they are connected, and since they are not working, we can't really use them anymore. Is there a way to know what they are connected to and control them ? Maybe i missed a new controller with some attributes in it ?

Here's my character i'm working on thanks to you !

![fff copy](https://user-images.githubusercontent.com/130797127/232252608-df0e51e7-4aa8-4b39-8db0-34555e667630.jpg)

**Comment by Obaemon7** [comment]
when i saw you were working on this, i thought about contacting you because i did all of those connections, so humanity didn't have to make this twice, but i realized after the fact that i have renamed all the blendshapes i connected (because those long names were annoying), and i will have to put all the original names back to make this usable, and i probably did an horrible and unprecise job with my nodes.

**Comment by stepharamburu** [comment]
Hi @danielbui78 
In my case, the bridge seems to works fine with G8.1 at the first try, then testing G8 doesn't work and now it is not working with G8.1 or G8 models anymore. Any suggest please? Thanks in advance!

![dazbridge1B](https://user-images.githubusercontent.com/89225543/232397210-e7682c15-1123-46f2-8f08-27d934a6796e.JPG)
![dazbridge1](https://user-images.githubusercontent.com/89225543/232397215-1fa5101b-3099-4de6-a672-d603c31cfd7f.JPG)
![dazbridge3](https://user-images.githubusercontent.com/89225543/232397216-b79deb7a-7baa-4412-ad7f-66eccde7ca3a.JPG)
![dazbridge2](https://user-images.githubusercontent.com/89225543/232397218-5faf8190-756e-4eaa-8d57-8d3630526844.JPG)

**Comment by danielbui78** [comment]
I just posted a hotfix for G8 "Tear.transparency" error, but I haven't had time to package a new maya plugin or DLL yet.  You can try it out by downloading the d2m.py file:

https://github.com/daz3d/DazToMaya/blob/c669fedcb97a79597ab2b7c7d8b0a3e2ad46f6d3/Maya/MAYA_APP_DIR/modules/DazToMaya/scripts/d2m.py

Then just replace the d2m.py inside your Maya modules\DazToMaya\scripts folder.

This hotfix fixes G8 related crashes, but there is an additional bug where blendshape targets are not being renamed and matched with the joint, so auto-JCM is not working yet for G8.  Based on your screenshot, it looks like G8.1 blendshape targets are not being renamed properly for you either.  What version of Daz Studio are you using?  Is it a Beta?

**Comment by stepharamburu** [comment]
@danielbui78 Daz v 4.21.0.5 Pro Edition (64 bit)

**Comment by stepharamburu** [comment]
> I just posted a hotfix for G8 "Tear.transparency" error, but I haven't had time to package a new maya plugin or DLL yet. You can try it out by downloading the d2m.py file:
> 
> https://github.com/daz3d/DazToMaya/blob/c669fedcb97a79597ab2b7c7d8b0a3e2ad46f6d3/Maya/MAYA_APP_DIR/modules/DazToMaya/scripts/d2m.py
> 
> Then just replace the d2m.py inside your Maya modules\DazToMaya\scripts folder.
> 
> This hotfix fixes G8 related crashes, but there is an additional bug where blendshape targets are not being renamed and matched with the joint, so auto-JCM is not working yet for G8. Based on your screenshot, it looks like G8.1 blendshape targets are not being renamed properly for you either. What version of Daz Studio are you using? Is it a Beta?

@danielbui78 excuse my ignorance but, How I can download that file please? :(

**Comment by danielbui78** [comment]
[d2m.py.zip](https://github.com/daz3d/DazToMaya/files/11247001/d2m.py.zip)

For future, just google instructions on "how to download single files from github repository".  There are more details and screenshots than I would have time to do right now.

**Comment by danielbui78** [comment]
@stepharamburu if you are still having the issue with G8.1, can you clear your Maya script editor log, then do the Daz Import operation then copy and paste the entire Maya script editor log into a text file and attach the file here?

**Comment by stepharamburu** [comment]
@danielbui78 Thanks for the advice :)  I replaced the file but the problem persist...  :(
It's very funny because @Obaemon7 hasn't the same issue as me using the same Genesis 8.1 character, Otherwise, I'm pretty sure it works for me just at the first time.

![dazbridge4](https://user-images.githubusercontent.com/89225543/232404748-6f163336-5794-4e74-b2f7-2f98778fec6b.JPG)

**Comment by stepharamburu** [comment]
> if you are still having the issue with G8.1, can you clear your Maya script editor log, then do the Daz Import operation then copy and paste the entire Maya script editor log into a text file and attach the file here?
here the file...

[dazbridge_script_editor.txt](https://github.com/daz3d/DazToMaya/files/11247094/dazbridge_script_editor.txt)

**Comment by danielbui78** [comment]
[updated scripts.zip](https://github.com/daz3d/DazToMaya/files/11248592/updated.scripts.zip)

@stepharamburu thanks for posting your logs, I found your issue as well as the issue with G8+Face Morphs: You are adding an additional morph that has a "-" (hypen) in the name.  The updated d2m.py and morphs.py should help fix those issues.  Please post any Maya script editor logs if you encounter python errors.

**Comment by stepharamburu** [comment]
Hi @danielbui78 Please, if you're referring to the p2m.py file you send me as zip file, I've got installed already before to send my script editor text. Probably there's a new updated file available?

**Comment by danielbui78** [comment]
Please click the link and download the "updated scripts.zip" that's in my last post.  That has two files in it just as I have indicated: d2m.py and morphs.py

**Comment by danielbui78** [comment]
@Obaemon7 No, but the d2m.py changes may unmask error messages that explain why your setup is not working.  Download and replace those two files.  If you receive errors in your Maya Script Editor log, please copy them into a text file and attach it here.

Just to clarify: I have verified that the following should have full blendshape eye + eyelid control:
1. Use G8.1F in Daz Studio 4.21 Pro
2. Exporting Morphs with Add Expressions: ARKit (Genesis8.1) button
3. Send to Maya via Bridge
4. Click Import Daz in Maya 2022
5. Click Auto Rig

With those steps, the Eye IK controls should move eyes and eyelid blendshapes like in the picture.
![eye IK blendshape controls](https://user-images.githubusercontent.com/11391924/232518180-c8bf4faa-fe33-4f87-b3ba-003a214e6d5b.gif)

The mouth controls are only attached to bones.  This is not intended to move the blendshapes.  To move mouth and jaw blendshapes, please use the Morphs node as in this picture:
![mouth morph controls](https://user-images.githubusercontent.com/11391924/232518621-26edce2d-f64c-4f60-a145-e0d6815a7d03.gif)

**Comment by Obaemon7** [comment]
Eyelids movement are working now, however, i think i'm gonna stick with the connections i did myself, multiple things don't seem to work properly, like the neck deformations (bend the neck back and forward you'll see). The blendshapes of the fingers are missing. 
I was hoping it would work so i don't have to do it again if i want to do an other character.
